package com.moseti.cutecats.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single user-uploaded image in the local database.
 *
 * @param id The unique identifier for the entry, auto-generated by Room.
 * @param uri The string representation of the image's content URI. We store the URI
 *            so the app can request permission to load it later.
 * @param timestamp The time the image was saved, used for sorting.
 */
@Entity(tableName = "user_uploads")
data class UserUpload(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val filePath: String,
    val timestamp: Long
)